---
# Apache
- name: Apache
  action: apt pkg=apache2 state=installed

- name: Apache Modules
  action: command a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: Apache | Copy Host Config
  action: template src=../files/vhost.conf dest=/etc/apache2/sites-available/vhost.conf

- name: Apache | Enable Host Config
  command: a2ensite vhost.conf
  notify: restart apache

- name: Apache | Disable Default Host Config
  command: a2dissite 000-default
  notify: restart apache

- name: Apache | Ensure application files are present
  file: path={{ document_root }} state=directory