---
- hosts: default
  sudo: true
  vars:
    subdomain: dev
    domain: "{{ subdomain }}.caffeinated.nl"
    document_root: "/var/www/phlybox"
  tasks:
    - include: tasks/common.yml
    - include: tasks/webserver.yml
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted